### ISSUE TITLE
Enable renovate

### ISSUE THREAD

**Issue by lmilbaum** [containers/bootc#184]
Every new version of the quay.io/centos-boot/fedora-tier-1 image will generate a PR in this repo which will invoke the CI with the new version

**Comment by cgwalters** [comment]
I think I'd be more interested in adding support for running this project's test suite against changes in the OS repository - and especially running test suites against the centos-boot image before it gets published.

**Comment by lmilbaum** [comment]
> I think I'd be more interested in adding support for running this project's test suite against changes in the OS repository - and especially running test suites against the centos-boot image before it gets published.

There are two approaches I can think of:
1. Invoke the test suites in centos-boot CI which will probably make the CI run quite long and not very effective
2. Invoke the test suites after the PRs are merged. That could gate the release promotion.  The result of it is maintaining few environment: dev, ci (pre-merge), test (post-merge, published to a test container registry), prod (published to the production container registry).  The promotion from a lower environment to a higher environment takes place when all environment quality gates are green.
Renovate in this case can pick up new versions landed in the production container registry.

WDYT?

**Comment by vrothberg** [comment]
@lmilbaum @cgwalters did we progress on this issue?

**Comment by lmilbaum** [comment]
> @lmilbaum @cgwalters did we progress on this issue?

This is an old one :-)
Renovate is already onboarded. But, I'm not sure it updates what @cgwalters mentioned in his comment.
