### ISSUE TITLE
bootc switch failed

### ISSUE THREAD

**Issue by HuijingHei** [containers/bootc#19]
Build bootc, and start FCOS with `--bind-ro`, run `./bootc switch --no-signature-verification quay.io/fedora/fedora-coreos:next` and get error.
```
# ./bootc status
*  e051d49946dd7685ed1fa52c924506fc997958fd002ab39f9b131d0c45b72bb0.0
    (Non-container origin type)

    Backend: ostree
    Booted: yes

# ./bootc switch --no-signature-verification quay.io/fedora/fedora-coreos:next
layers stored: 0 needed: 51 (693.8 MB)
 1.32 MiB [████████████████████] (0s) Fetched ostree chunk sha256:10b8c17c44e6
error: Invalid ref name fedora:fedora/x86_64/coreos/next
```

Another question, does `bootc switch` have the same func with `rpm-ostree rebase <container image>` ?

**Comment by cgwalters** [comment]
> error: Invalid ref name fedora:fedora/x86_64/coreos/next

That's...odd.  Can you paste the output of `rpm-ostree status` here too?

> Another question, does bootc switch have the same func with rpm-ostree rebase <container image> ?

Yep, that's exactly the idea!  (bootc *only* supports containers note)

**Comment by HuijingHei** [comment]
Thanks @cgwalters for the confirm. This is the output:
```
[root@cosa-devsh ~]# rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: inactive; periodically polling for updates (last checked Wed 2022-12-07 01:52:49 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/next
                  Version: 37.20221127.1.0 (2022-11-28T10:24:58Z)
                   Commit: e051d49946dd7685ed1fa52c924506fc997958fd002ab39f9b131d0c45b72bb0
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
```

**Comment by cgwalters** [comment]
With our stock containers, you can use
`bootc switch --ostree-remote=fedora quay.io/fedora/fedora-coreos:stable` - note `--ostree-remote=fedora` enables *the same GPG verification* that we use for "native" ostree fetches.

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/23 !

**Comment by HuijingHei** [comment]
Thanks @cgwalters for the quick fix!
