### ISSUE TITLE
Hook into https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#21]
I think it'd make sense to have this project also shipped in the big https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/packages/ COPR repo for Fedora.

**Comment by cgwalters** [comment]
What's the pattern to follow for this?  I see https://github.com/containers/netavark/blob/main/netavark.spec.rpkg - is that in use?

**Comment by anthr76** [comment]
It appears as so https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/package/netavark/ it looks like it's activated from a GitHub webhook. If a spec isn't already written I'm happy to take a try.

**Comment by cgwalters** [comment]
There's also https://packit.dev/ too...

**Comment by cgwalters** [comment]
OK, I made significant progress on this after https://github.com/containers/bootc/pull/36
and https://copr.fedorainfracloud.org/coprs/walters/bootc/ is now up.

So...let's basically move that to say https://copr.fedorainfracloud.org/coprs/rhcontainerbot/bootc ?

**Comment by lsm5** [comment]
> I think it'd make sense to have this project also shipped in the big https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/packages/ COPR repo for Fedora.

sure thing. You now have full access to that copr now.

> What's the pattern to follow for this? I see https://github.com/containers/netavark/blob/main/netavark.spec.rpkg - is that in use?

Yes, a spec like that in the main bootc dir and a github webhook https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/integrations/ 

Podman, Buildah and Skopeo use similar specs.

**Comment by lsm5** [comment]
> OK, I made significant progress on this after #36 and https://copr.fedorainfracloud.org/coprs/walters/bootc/ is now up.
> 
> So...let's basically move that to say https://copr.fedorainfracloud.org/coprs/rhcontainerbot/bootc ?

I can set that up too if you prefer a separate one.

**Comment by cgwalters** [comment]
> sure thing. You now have full access to that copr now.

Oops, I think I somehow thought I was requesting permissions for the rhcontainerbot/ namespace, not the podman-next.

I think we do actually want a separate bootc one.

It seems like rhcontainerbot is a user account and not a group?  It'd seem to make sense to have a group instead, like we do with e.g. https://copr.fedorainfracloud.org/coprs/g/CoreOS/

But anyways, for now can you create a rhcontainerbot/bootc project and add me - or even just the existing CoreOS FAS group as admins?

**Comment by cgwalters** [comment]
This is done!  Thanks everyone!
