### ISSUE TITLE
Running `install to-disk` fails on Debian

### ISSUE THREAD

**Issue by mvo5** [containers/bootc#279]
When trying to explore the images that bootc generates to explore how/if  `bootc-image-builder` could use it directly (or for a start ensure the generated images are similar enough) I ran into the following issue on a standard Debian/unstable system:
```
$ podman --version
podman version 4.7.2

$ truncate -s 10G test-disk.img
$ sudo losetup -f test-disk.img

$ sudo podman run --env RUST_LOG=error,bootc_lib::install=debug  --rm --privileged --pid=host --security-opt label=type:unconfined_t quay.io/centos-bootc/fedora-bootc:eln bootc install to-disk /dev/loop2
DEBUG Target image reference: ostree-unverified-registry:quay.io/centos-bootc/fedora-bootc:eln
DEBUG Fetched manifest with digest sha256:145383779c284eab7e8067219dd0249532b4d9d77861bd74c029a53e07b59ce9
DEBUG Retargeting /tmp to host
ERROR Linking tmp mounts to host: Exchanging /tmp <=> /tmp.tmp: Invalid cross-device link (os error 18)
```
podman is slightly older on Debian so maybe that is the issue already. I tried both the normal /tmp and /tmp on a tempfs with the same error.

Certainly not high priority but I wanted to report it anyway for completeness. I ran the same on fedora-39 but got a different error, I will report this as a separate issue.

**Comment by cgwalters** [comment]
This looks like a dup of https://github.com/containers/bootc/issues/95 so it apparently still exists.

I will try to spin up a Debian environment at some point, should be a [blast from the past](http://web.archive.org/web/20020802202859/http://people.debian.org/~walters/)

**Comment by cgwalters** [comment]
Well, I didn't dig in too deep because https://github.com/containers/bootc/pull/284/commits/f2d5949fc8ced139c75f62bab2b897ef5ed520b4 fixes this.  IOW it works with `fedora-bootc-dev:eln` now.

**Comment by cgwalters** [comment]
Well actually testing on debian stable, the next problem was that its kernel `xfs.ko` is too old to mount the filesystems created by the Fedora ELN `mkfs.xfs`.  However, this worked for me:

```
$ truncate -s 10G /var/tmp/disk
$ podman run --env RUST_LOG=error,bootc_lib::install=debug  --rm --privileged --pid=host -v /var/tmp:/output --security-opt label=type:unconfined_t quay.io/centos-bootc/centos-bootc-dev:stream9 bootc install to-disk --disable-selinux --wipe --generic-image --via-loopback /output/disk
```

**Comment by mvo5** [comment]
Thank you, this works now on my unstable system which is super nice!

**Comment by mvo5** [comment]
> This looks like a dup of #95 so it apparently still exists.
> 
> I will try to spin up a Debian environment at some point, should be a [blast from the past](http://web.archive.org/web/20020802202859/http://people.debian.org/~walters/)

Heh, I did quite a bit of work on apt so I know your apt-secure patches (and of course your cdbs work) - great stuff!
