### ISSUE TITLE
remove note line from `bootc status --json`

### ISSUE THREAD

**Issue by beav** [containers/bootc#297]
The output of `bootc status --json` has the following line before the json starts:

```
note: The format of this API is not yet stable
```

I have some logic that captures the output, but it captures both STDERR and STDOUT which breaks json parsing.

We can fix our parsing, but the smallest fix would be to remove the "note" from the output. The json has a field with `"apiVersion":"org.containers.bootc/v1alpha1"` which IMO conveys the same thing as the note in a machine-readable way.

**Comment by cgwalters** [comment]
> but it captures both STDERR and STDOUT which breaks json parsing.

As a general rule though...I think part of the design of Unix having a distinct stderr stream is precisely for use cases like this.  I can't imagine it's hard to change the calling tool to capture stderr separately, is it?

Nevertheless I think your overall point is valid, so PR in https://github.com/containers/bootc/pull/298
