### ISSUE TITLE
Add `rollback` verb

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#383]
My original hope was that we'd get away from an imperative-style interface; `bootc edit` should allow programmatic targeting for scripting cases.

However, a `bootc rollback` verb would be highly convenient.

**Comment by cgwalters** [comment]
We chatted about this in realtime, I was pushing for a "rollback via targeting previous image tag or sha256 digest" flow.  The problem with doing this via sha256 digest is that many default registry configurations aggressively GC untagged images.  

So our entrypoint docs should probably push for a workflow of pushing at least two versioned tags per build, a `:latest` equivalent and a versioned tag.  

This all said, there's still a clear use case and value for the low-level technique of reverting to the previous boot entry; it's particularly needed for cases where networking breaks after upgrade, etc.

**Comment by vkrizan** [comment]
Hello,

I'm trying to help out with the support of [greenboot](https://github.com/fedora-iot/greenboot) with bootc. I had similar thought regarding adding the `rollback` verb to the CLI. This verb would be a bit crucial for such support on the greenboot side.

Does bootc or ostree native containers keeps (caches) the rollback image? My understanding is that the variant with ostree keeps the deployment in the systems for a rollback. Can that be done in similar way with the bootc-compatible container images (if the idea is to have bootc "engine" agnostic or not having hard dependency on ostree)?

Thank you.

cc @beav

**Comment by vkrizan** [comment]
@say-paul My idea was to extend greenboot to use `bootc rollback` for bootc systems, however the rollback verb is not yet available (this issue) and I've hit the bootloop issue (https://github.com/fedora-iot/greenboot/issues/135). I might try to contribute this verb to bootc, but I'm not sure if Colin's concerns regarding GC is a blocker for that. (And my Rust knowledge is rusty :-)

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/447

**Comment by runcom** [comment]
closed with https://github.com/containers/bootc/pull/447 (?)
