### ISSUE TITLE
Ensure no-selinux case is at least e2e tested periodically

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#419]
This issue tracks our "full" support for installing SELinux-enabled targets from SELinux-disabled hosts.

**Comment by albertofaria** [comment]
FWIW, [crun-vm](https://github.com/containers/crun-vm) will make use of this as part of its support for running bootc containers.

**Comment by larsks** [comment]
Running a bootc build...

```
root@host:~# podman run \
  --rm \
  -it \
  --privileged \
  --pull=newer \
  --security-opt label=type:unconfined_t \
  -v "$PWD/output:/output" \
  -v /var/lib/containers/storage:/var/lib/containers/storage \
  "$BUILDER" \
  --type qcow2 \
  --local \
  bootc-test-image
```

...I was directed here by this warning:

```
Host kernel does not have SELinux support, but target enables it by default; this is less well tested.  See https://github.com/containers/bootc/issues/419
```

And yet selinux is both present and enabled on the host:

```
root@host:~# getenforce
Enforcing
```

What's going on here?

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/790
