### ISSUE TITLE
RFE: add bootc rollback

### ISSUE THREAD

**Issue by mrguitar** [containers/bootc#429]
What do you all think about adding a rollback option in bootc? If feels strange to use bootc for things like update, switch, but not rollback. I suppose if we draw a line that bootc *only* syncs a system w/ what's available in a registry (or local store), and therefore, rollbacks are out of scope and *should* only be in rpm-ostree. ....but it still feels odd to me.

**Comment by cgwalters** [comment]
Dup of https://github.com/containers/bootc/issues/383 I believe

**Comment by mrguitar** [comment]
whoops! I promise to search first next time. :)
Thanks for closing.

**Comment by cgwalters** [comment]
Initial PR up in https://github.com/containers/bootc/pull/447
