### ISSUE TITLE
unlabeled_t after `bootc install to-disk` with BOOTC_SETENFORCE0_FALLBACK=1

### ISSUE THREAD

**Issue by albertofaria** [containers/bootc#482]
I'm running a bootc container under [krun](https://github.com/containers/crun/blob/main/krun.1.md). The entrypoint/PID 1 is /bin/sh running a script that forks bootc:

```console
RUST_LOG=debug BOOTC_SETENFORCE0_FALLBACK=1 \
    bootc install to-disk \
    --source-imgref oci-archive:/output/image.oci-archive \
    --target-imgref "$image_name" \
    --skip-fetch-check \
    --generic-image \
    --via-loopback \
    --karg console=tty0 \
    --karg console=ttyS0 \
    /output/image.raw
```

bootc is run with context "kernel", which it attempts to modify to have type install_t. This fails for reasons I've still to figure out, but can be worked around with BOOTC_SETENFORCE0_FALLBACK=1. I don't know if this is the root cause of the following issue.

The VM image is generated successfully and boots, but a lot of SELinux errors are spewed out during boot, making the guest unusable:

```
[    0.289474] audit: initializing netlink subsys (disabled)
[    0.291487] audit: type=2000 audit(1713783734.244:1): state=initialized audit_enabled=0 res=1
[    1.747538] systemd-journald[352]: Collecting audit messages is disabled.
[    3.479826] audit: type=1404 audit(1713783736.698:2): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
[    3.562909] audit: type=1403 audit(1713783736.781:3): auid=4294967295 ses=4294967295 lsm=selinux res=1
[    4.113839] audit: type=1400 audit(1713783737.332:4): avc:  denied  { search } for  pid=636 comm="systemd-rc-loca" name="etc" dev="vda4" ino=4829514 scontext=system_u:system_r:systemd_rc_local_generator_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
[    4.123033] audit: type=1400 audit(1713783737.332:5): avc:  denied  { search } for  pid=636 comm="systemd-rc-loca" name="etc" dev="vda4" ino=4829514 scontext=system_u:system_r:systemd_rc_local_generator_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
...
```

Note the "tcontext=system_u:object_r:**unlabeled_t**:s0". It looks like the disk needs relabeling.

Is this an issue with bootc or on my end?

**Comment by cgwalters** [comment]
> I'm running a bootc container under [krun](https://github.com/containers/crun/blob/main/krun.1.md).
> bootc is run with context "kernel",

I think that's because no SELinux policy is being loaded in this userspace, right?  It's basically doing "run a container image as a VM", which currently conflicts with what bootc expects.

Now, in practice...hmm, we'd need to check if `kernel` has the `mac_admin` capability or not.  Based on a quick glance at https://github.com/search?q=org%3Afedora-selinux%20mac_admin&type=code I don't think it does...

We could of course just detect this situation and run `setenforce 0`.

Actually, what is even the point of having SELinux enabled in krun if everything is run as `kernel_t`?  Shouldn't it boot by default with `selinux=0` then or even have it disabled in the host kernel?

**Comment by albertofaria** [comment]
> I think that's because no SELinux policy is being loaded in this userspace, right? It's basically doing "run a container image as a VM", which currently conflicts with what bootc expects.

Right.

> We could of course just detect this situation and run setenforce 0.

That's what's being done, but the issue persists.

> Actually, what is even the point of having SELinux enabled in krun if everything is run as kernel_t? Shouldn't it boot by default with selinux=0 then or even have it disabled in the host kernel?

Disabling SELinux altogether did the trick! I was assuming that it was needed for the relabeling to work properly.

My original issue is fixed. Thanks for the help. Feel free to close this if there's nothing else to be followed up on.

**Comment by cgwalters** [comment]
There may be a way to better handle "selinux enabled in kernel but disabled at runtime" even than setting `selinux=0`.  IIRC Debian has it this way https://wiki.debian.org/SELinux/Setup
But, given that `selinux=0` works I think it is the correct thing.
