### ISSUE TITLE
Add opinionated but configurable automatic updates

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#5]
Let's steal some of the logic and code from https://github.com/coreos/zincati/blob/main/docs/usage/auto-updates.md

**Comment by lmilbaum** [comment]
I'd suggest considering renovatebot as the framework for auto-updating. We can contribute to the [project](https://github.com/renovatebot/renovate) in case it doesn't support this use case.

**Comment by anthr76** [comment]
Big +1 for renovate. Although I'm not sure how it would work in the model unless a "treefile" is somewhat tracked by GitOps

**Comment by LorbusChris** [comment]
@lmilbaum as I understand it, this issue is about updating a bootc OS deployment, not about updating code dependencies in this repo. So to me that sounds rather unrelated to renovate.

**Comment by LorbusChris** [comment]
@cgwalters are you planning on adding support for Cincinnati in bootc, or do you have an alternative in mind?
I think it'd be interesting to investigate ways of distributing the update metadata through OCI registries, instead of Cinci.

**Comment by LorbusChris** [comment]
also ref https://github.com/coreos/fedora-coreos-tracker/issues/1263

**Comment by cgwalters** [comment]
> @cgwalters are you planning on adding support for Cincinnati in bootc, or do you have an alternative in mind?

IMO no; that's exactly the kind of thing that can live as a higher level project.  A *huge* difference here vs e.g. FCOS is the emphasis (and raw ability) to trivially derive builds.  And one of those things that's now easy to inject is a custom tool to do OS updates.

**Comment by cgwalters** [comment]
This was fixed by https://github.com/containers/bootc/pull/179
