### ISSUE TITLE
Documentation site is unavailable

### ISSUE THREAD

**Issue by aphedges** [containers/bootc#532]
<https://containers.github.io/bootc/>, which is linked to from both GitHub and the README, is unavailable. Visiting the URL only displays a 404 page.

**Comment by aphedges** [comment]
@jmpolom, is your :-1: reaction signifying that you are not experiencing the problem or that you believe this issue is itself problematic, or did you intend some other meaning?

**Comment by jmpolom** [comment]
> @jmpolom, is your 👎 reaction signifying that you are not experiencing the problem or that you believe this issue is itself problematic, or did you intend some other meaning?

I noticed the docs website appeared broken. Thumbs down resonated more with me than up.

**Comment by cgwalters** [comment]
I think this must relate to https://github.com/containers/bootc/pull/523 but not sure how yet.  The action run is green.

**Comment by aphedges** [comment]
I can confirm it works now. Thanks!
