### ISSUE TITLE
Problems installing postfix (due to symbolic linked directory)

### ISSUE THREAD

**Issue by sigulete** [containers/bootc#545]
When installing `postfix` in a container image based on `fedora-bootc`, I noticed that the file  /usr/sbin/sendmail is not created.
It affects other applications that rely on this file.

The directory `/var/lib/alternatives` is a symbolic link to `/usr/lib/alternatives`. I'm assuming this is causing the problem.

![Screenshot](https://github.com/containers/bootc/assets/35115643/0ac442d3-e936-4791-bd29-414980ed6e3d)

**Comment by sigulete** [comment]
Additional information, other packages using `alternatives` have similar issues.
I installed `man-db`, and it doesn't create `/usr/bin/man`. Looking at a regular Fedora Server, `/usr/bin/man` is a symbolic link to `/usr/lib/alternatives`.

**Comment by sigulete** [comment]
Considering that this may be an issue with the implementation, I have opened a ticket in bugzilla (fedora container images):
https://bugzilla.redhat.com/show_bug.cgi?id=2281575

**Comment by cgwalters** [comment]
This issue doesn't relate to bootc itself, but a specific OS.  There's already a tracker issue for this here: https://gitlab.com/fedora/bootc/tracker/-/issues/7
