### ISSUE TITLE
Bootc with credential helper fails without /etc/ostree/auth.json

### ISSUE THREAD

**Issue by p5** [containers/bootc#562]
A bit of a strange one, and I'm not too sure where to file this.

I am trying to deploy a bootc image to AWS, with the image hosted in ECR.  To pull from ECR, it's best to use the [docker-credential-ecr-login helper](https://github.com/awslabs/amazon-ecr-credential-helper).  I don't know if any of this information about the credential helpers is actually relevant, but I do not currently have an environment to test without.

So I added the credential helper binary to my $PATH, along with the following `/etc/containers/registries.conf.d/001-ecr-login.conf` config:

```
credential-helpers = ["ecr-login"]
```

A bootc upgrade failed with "authentication required".

Now comes the weird part.  If I create an empty `/etc/ostree/auth.json` file, an upgrade works... 

If this is a required file, I suggest a relevant error message be thrown when not present.  Or specifying this somewhere in the docs would also be good.

Thank you
Rob

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/563 for docs, sorry it's going to be hard for us to do better in a short term.

**Comment by p5** [comment]
Updating the docs is great, thanks!  Just don't want others to get stuck on this for as long as I did :laughing: 

I don't mind whether you close this as complete, or leave it in the hope it will be fixed further down the line.
