### ISSUE TITLE
File containing booted image metadata

### ISSUE THREAD

**Issue by p5** [containers/bootc#568]
As an Infrastructure Engineer
I want to be able to read metadata about the booted image from the filesystem
So that I can use this information inside system containers

I am implementing a systemd container service (quadlet) which monitors the booted image and sends periodic reports to AWS CloudWatch (or could by any external service).  This will be used to make sure none of the servers are falling behind on updates.
This service requires access to metadata about the currently deployed image, like the digest or labels.

As far as I could tell, there's no consistent location where this information is stored (like an `/etc/os-release` for bootc images), so I must have a pre-exec step in my Systemd unit which pipes `bootc status` or `rpm-ostree status --json` to a file which my container mounts.

It would be great if bootc maintains a single location containing metadata about the booted image for any service to mount and read from.  It could be stored somewhere like `/run/bootc/deployed-image.json`, created on boot and updated on bootc write operations (update/rollback/switch).

Filing this in response to my questions in Matrix.

Thank you
Rob

**Comment by cgwalters** [comment]
I get the idea, but on the flip side, for such systems management containers you are very likely to need to expand the use case beyond "state that can be directly read from files" - for example systemd unit state right?

> so I must have a pre-exec step in my Systemd unit which pipes bootc status or rpm-ostree status --json to a file which my container mounts.

Such a container image when run privileged can bind mount e.g. `/run/systemd` and the systemd dbus socket, and use that to invoke arbitrary code on the host.  For example, you can invoke `systemd-run -qPG bootc status --json`.

**Comment by p5** [comment]
> Such a container image when run privileged can bind mount e.g. /run/systemd and the systemd dbus socket, and use that to invoke arbitrary code on the host. For example, you can invoke systemd-run -qPG bootc status --json.

I was not aware you are able to do this, and it sounds like a far better approach than mounting and reading a file.  Thank you!

Although a general /etc/os-release integration may be good :eyes: 

Will close this, as my use-case has now been resolved.
