### ISSUE TITLE
restricting main branch to "[ ] Require pull request before merging" is being reverted

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#57]
I want to make reviews required by default on this project (as they should be on most).

I can make the change successfully in the web UI, but it seems like something is reverting it later.  Is there some automation on the containers/ GH org that is doing something like this?

**Comment by cgwalters** [comment]
cc @baude @cevich - any ideas?

**Comment by baude** [comment]
I am not aware of anything being set.  If it is, it is likely an accident.

**Comment by cevich** [comment]
I too am unaware, didn't even know overriding it at the org-level was possible (is it?).

**Comment by cevich** [comment]
Just looked through all the org-level settings and didn't find anything that would change settings like that.  Hmmm.  We do have 10-something apps setup on the org., it's entirely possible one is responsible but none jump out at me.  I'll take the list to the team and see which ones we can disable/remove.

**Comment by cgwalters** [comment]
Thanks Chris.  Whatever is reverting it seems to be running on a roughly daily schedule.  The setting lasted for hours at least last time I tried it.

**Comment by cgwalters** [comment]
Ah, the [audit log](https://github.com/organizations/containers/settings/audit-log?q=repo%3Acontainers%2Fbootc++) makes it very obvious:

![image](https://user-images.githubusercontent.com/244096/217090383-61b325f3-cdd8-4923-9f39-31aa787950af.png)

Will try to talk to the Prow team to see how to fix that.

**Comment by cgwalters** [comment]
Semi-blindly trying https://github.com/openshift/release/pull/36102

**Comment by cgwalters** [comment]
@baude not urgent but https://github.com/openshift/release/pull/36102#issuecomment-1419893277 when you get a chance

**Comment by cgwalters** [comment]
@cevich is it the case today that all the other repositories in the containers org that have Prow jobs also use Prow to merge (i.e. with approve/lgtm + tide)?

**Comment by cevich** [comment]
Unfortunately no, not all 100-some odd repos, Red Hat doesn't maintain all of them.  Off-hand, it's about 15-20 repos that use Prow.

**Comment by vrothberg** [comment]
@cgwalters, did you resolve the issue in the meantime?

**Comment by cgwalters** [comment]
Yes, we dropped Prow for now
