### ISSUE TITLE
create milestones

### ISSUE THREAD

**Issue by vrothberg** [containers/bootc#572]
I want to discuss the idea of creating milestones. At the present, I find it hard to figure out which issues, bugs and deliverables are immediately relevant for GA. I see a bit of scattering across various repositories and Jira. To reduce overhead, I think that milestones on GitHub may help us in a) reducing administrative overhead and b) helping stakeholders figure out where we are.

What I currently have in mind is to create Jira cards pointing to milestones on GitHub (in this case related to bootc).  This way, we don't have to replicate issues/cards in GitHub and Jira.  The milestones may further help us pick work items.  The Podman Desktop team is a heavy use of GitHub milestones and found it a quite productive use of time.

@cgwalters WDYT?

**Comment by cgwalters** [comment]
There is already a 1.0 milestone https://github.com/containers/bootc/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

I am totally happy to make more use of that especially with automation syncing to interested downstreams.

**Comment by vrothberg** [comment]
Is the 1.0 milestone intended to align with GA?

> I am totally happy to make more use of that especially with automation syncing to interested downstreams.

Thanks, that would be great!  Currently, there's 1 issue under the milestone but I assume we can move more under it?

**Comment by cgwalters** [comment]
> Is the 1.0 milestone intended to align with GA?

Yes.

> Thanks, that would be great! Currently, there's 1 issue under the milestone but I assume we can move more under it?

Yep of course

**Comment by vrothberg** [comment]
Thanks!
