### ISSUE TITLE
Document additional requirements for contributions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by m8ram** [containers/bootc#574]
Please explain what is required to contribute to this project.
E.g. The need to us `--signoff` in commit messages. Ideally with a bit of explanation about (or link to) DCO. What it is, why it's important etc.

**Comment by richardfontana** [comment]
Perhaps this text could be reused or adapted:
https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs
