### ISSUE TITLE
Please provide a way to inspect if a container is bootc enabled

### ISSUE THREAD

**Issue by mvo5** [containers/bootc#599]
We are looking for a way to detect if a container is bootc enabled. 

One possible way would be do show something when running `bootc status` from inside a bootc enabled container.

But AFAICT today there is no indication in the output:
```sh
$ sudo podman run -it --pull=newer --entrypoint bash  quay.io/centos-bootc/centos-bootc:stream9
bash-5.1# bootc status
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image: null
  bootOrder: default
status:
  staged: null
  booted: null
  rollback: null
  rollbackQueued: false
  type: null
```
which is similar to the output that I get when running "bootc status" on my non-bootc enabled fedora-40 system.

**Comment by cgwalters** [comment]
> We are looking for a way to detect if a container is bootc enabled.

A container or an image?  For images we have a standard label: https://github.com/containers/bootc/blob/559aca65e31dd6aa0ab7dbeffbe77da5faa3c361/docs/src/bootc-images.md?plain=1#L54

But yes, it wouldn't be hard to expose this via the status too if that'd be useful.

**Comment by mvo5** [comment]
Thank you! I think we can go with the label if every bootc container has it that is good enough.
