### ISSUE TITLE
Doc build fails

### ISSUE THREAD

**Issue by jmarrero** [containers/bootc#71]
```
Run actions/configure-pages@v3
Error: Get Pages site failed
Error: HttpError: Not Found
```

**Comment by cgwalters** [comment]
Thanks for filing this; I only briefly looked at it but couldn't figure it out.  When I originally added the docs option I just picked one that seemed like it'd work, and I'd swear I had tested it in my actions fork originally.

Dunno.  Probably better to try cloning an existing docs CI setup; maybe that in e.g. [coreos-installer](https://github.com/coreos/coreos-installer/tree/main/docs) ?

**Comment by jmarrero** [comment]
Apparently the only thing we need to do for the current setup to work is to change the source in  https://github.com/containers/bootc/settings/pages to Github Actions. That option is the first dropdown in the page.

However I got no access on the main repo to do that.

I got it working using that on my fork:
https://jmarrero.github.io/bootc/

**Comment by jmarrero** [comment]
@cgwalters changed the setting, now we have a good doc build: https://containers.github.io/bootc/

**Comment by cgwalters** [comment]
Yes!  https://containers.github.io/bootc/ Now time to merge the bits from README.md with that...
