### ISSUE TITLE
Unable to do bootc image copy-to-storage

### ISSUE THREAD

**Issue by ckyrouac** [containers/bootc#725]
[This commit](https://github.com/containers/bootc/commit/8b301281fff5c75d1040f13b55d1505607515169#diff-fe45e8cd8b566039edc4c6a4e80f355754d32078b45e465a407e22e27c39741aR658) appears to be the culprit. Using [the commit prior](https://github.com/containers/bootc/commit/321c79b84c59a5328a24476f3af3d90729900fd4), copy-to-storage works. Afaict the introduction of deploy::pull to the install path caused this problem. This breaks the existing tmt tests.

Reproduction steps:

- git checkout 8b301281fff5c75d1040f13b55d1505607515169
- podman build -t localhost/bootc -f hack/Containerfile .
- podman-bootc run localhost/bootc
- bootc image copy-to-storage
- error:

```
[root@localhost ~]# bootc image copy-to-storage
Copying local image docker://localhost/bootc:latest to containers-storage:localhost/bootc ...
ERROR Pushing image: Export: Copying image: No such image
```

Some initial debugging by @cgwalters showed the pulled image has the sha digest attached.

**Comment by cgwalters** [comment]
This was fixed by https://github.com/containers/bootc/pull/726
