### ISSUE TITLE
Failed to run bootc install to-existing-root on ppc64le host when using MBR partitioning

### ISSUE THREAD

**Issue by shi2wei3** [containers/bootc#742]
Steps:
1. install Fedora-Rawhide-20240730.n.0 Server on ppc64le host (ibm-p9z-06-lp7) with ks (`autopart --nohome --noswap --fstype=xfs --type=plain`)
2. run `podman run --tls-verify=false --rm --privileged --pid=host --security-opt label=type:unconfined_t -v /var/lib/containers:/var/lib/containers -v /:/target quay.io/fedora/fedora-bootc:41 bootc install to-existing-root`

Error message:
```
Installing to `dos` format partitions is not recommended
Initializing ostree layout
Initializing sysroot
ostree/deploy/default initialized as OSTree stateroot
layers already present: 0; layers needed: 65 (735.6 MB)
Fetched layers: 701.56 MiB in 2 minutes (5.79 MiB/s)
Deploying container image...done
Injected: etc/tmpfiles.d/bootc-root-ssh.conf
[31mERROR[0m Installing to filesystem: Installing bootloader: Failed to find PReP partition with GUID 9E1A2D38-C612-4316-AA26-8B49521E5A8B
```

Partition info:
```
# lsblk -o NAME,PARTTYPE
NAME   PARTTYPE
sda
??sda1 0x41
??sda2 0x83
??sda3 0x83
zram0

# blkid /dev/sda1 -p
/dev/sda1: PART_ENTRY_SCHEME="dos" PART_ENTRY_UUID="ef67d7a1-01" PART_ENTRY_TYPE="0x41" PART_ENTRY_FLAGS="0x80" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="8192" PART_ENTRY_DISK="8:0"
```

**Comment by shi2wei3** [comment]
Thanks for looking into this, I use beaker for this test and the default kickstart template use dos instead of gpt, so I specify my own kickstart as a workaround and the bootc install works well on ppc64le now.

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/745
