### ISSUE TITLE
Opening ostree/bootc/storage: No such file or directory

### ISSUE THREAD

**Issue by henrywang** [containers/bootc#747]
Install bootc image with anaconda or bib anaconda-iso. Run `bootc status` failed with error `ERROR\e[0m Status: Initializing storage: Opening imgstorage: Opening ostree/bootc/storage: No such file or directory (os error 2)"`

1. This issue can only be found in anaconda and bib anaconda-iso scenarios.
2. Did not run into this issue yesterday.
3. bib cross arch build (build aarch64 on x86_64) ami image has this issue as well (https://artifacts.osci.redhat.com/testing-farm/9cbff2f9-245d-482a-9b9d-fb2977f6a407/)

Issue should be caused by PR https://github.com/containers/bootc/pull/724.

e2e test in this repo does not cover anaconda test. The [bootc for rhel gating test](https://gitlab.com/redhat/rhel/bifrost/tests/bootc-image/-/issues/11) and [fedora rawhide gating test](https://gitlab.com/fedora/bootc/tests/bootc-workflow-report/-/issues/288) caught this issue.

**Comment by cgwalters** [comment]
Ugh, yes...basically this is hitting https://github.com/rhinstaller/anaconda/discussions/5197

I guess for now...hmm...I think we can do a workaround. Actually it's the same thing we'd need to do for in-place updates from prior systems! Which is definitely a test we need.

**Comment by henrywang** [comment]
bib cross arch build hits this error as well in https://artifacts.osci.redhat.com/testing-farm/9cbff2f9-245d-482a-9b9d-fb2977f6a407/.

It's not anaconda related.
