### ISSUE TITLE
RFE: switch should have an --apply option to speed up reboots

### ISSUE THREAD

**Issue by mrguitar** [containers/bootc#770]
`bootc upgrade --apply` is really nice when working with systems and forcing the update to take effect w/ a reboot. It seems like `switch` should have that same ability.  Thoughts? Is this easy to add?

**Comment by vrothberg** [comment]
2 hours from the request to an open PR.   You 🪨 !

**Comment by mrguitar** [comment]
Why does jira even exist!? ;)
