### ISSUE TITLE
install: Port to sfdisk

### ISSUE THREAD

**Issue by henrywang** [containers/bootc#774]
Port from gdisk to sfdisk (util-linux) as gdisk is less well maintained and is specifically targeted to be dropped from RHEL10 (xref https://issues.redhat.com/browse/RHELMISC-6651 )

---

# Original issue

`bootc install to-disk` failed with error `ERROR Installing to disk: Creating rootfs: Failed to run sgdisk: No such file or directory (os error 2)`. It's found in Fedora rawhide only. Do we need add `sgdisk` as dependence of bootc RPM package? Thanks.

Run command `sudo podman run --rm --privileged --tls-verify=false --pid=host --security-opt label=type:unconfined_t -v /var/lib/containers:/var/lib/containers -v /dev:/dev -v .:/output -e BOOTC_SETENFORCE0_FALLBACK=1 192.168.100.1:5000/hidden:ty1l bootc install to-disk --filesystem ext4 --root-ssh-authorized-keys /output/id_rsa.pub --generic-image --via-loopback /output/disk.raw`

**Comment by cgwalters** [comment]
https://gitlab.com/fedora/bootc/base-images/-/merge_requests/41
