### ISSUE TITLE
install: switch to doing dynamic mounts

### ISSUE THREAD

**Issue by cgwalters** [containers/bootc#826]
Moving this to a targeted issue from https://github.com/containers/bootc/issues/380

Basically let's switch to using [dynamic mounts](https://brauner.io/2023/02/28/mounting-into-mount-namespaces.html) for e.g. `/dev` and `/var/lib/containers` etc. This would help drop out a lot of the boilerplate from our install invocations.

**Comment by omertuc** [comment]
(Sorry I'm discussing BIFROST-532 instead of #826)

**Comment by cgwalters** [comment]
I took a look at `--security-opt` in https://github.com/containers/bootc/issues/928 - but changing that will become a conflict fest with https://github.com/containers/bootc/pull/919 so let's get that in first please.
