### ISSUE TITLE
etc tombstone removal

### ISSUE THREAD

**Issue by kfox1111** [containers/bootc#834]
If new files show up in an image destined for /etc, they show up. If a user ever writes/overwrites a file, it gets moved to persisted state, so theirs always wins. So far so good.

If you delete the file from etc, its delete is persisted too. So, seems like there is a tombstone somewhere marking that state. I'd like to find and delete the tombstone so that it reverts back to using the file provided by the image. How do you do this?

**Comment by kfox1111** [comment]
Oh, interesting.

**Comment by kfox1111** [comment]
Would it make sense to add something to bootc to make that more discover-able?

bootc reset-etc /etc/foo

or something that wraps around that?

**Comment by cgwalters** [comment]
Yes, I think it's a sub-thread of https://github.com/containers/bootc/issues/404 so marking as a dup.
