### ISSUE TITLE
Unable to bootc switch again after migrating silverblue to fedora-bootc

### ISSUE THREAD

**Issue by Perpixel** [containers/bootc#855]
Hello, not sure if this is working as expected, but I'm trying to test migration from a rpm-ostree Silverblue system to bootc on a qemu vm before doing it to my own workstation.

- Installed Silverblue:40, layered bootc. - OK
- bootc switch quay.io/fedora/fedora-bootc:40 - OK
- bootc switch quay.io/fedora/fedora-bootc:41 - OK
- bootc switch --transport oci-archive /tmp/custom-fedora-bootc.tar.gz - Staged but gone on reboot
- bootc switch quay.io/fedora/fedora-bootc:42 - Staged but gone on reboot

My system seems now stuck with only 2 deployments of fedora-bootc 40 and 41.

The documentation is not super clear on the right path to take to make this transition, so maybe it's just me?

Thanks

**Comment by Perpixel** [comment]
Just did the same step again on a clean VM, and now it works... Only this time I started from Silverblue:41

**Comment by Perpixel** [comment]
I was able to repro this if anyone interested. On reboot it probably fail in the deployment and reboot because I got a grub selection screen.

![Image](https://github.com/user-attachments/assets/502bf80e-aa87-4722-9bab-b47062afeaff)
![Image](https://github.com/user-attachments/assets/c58237c2-5adf-47fc-95fc-a7441432439c)

**Comment by ryanabx** [comment]
I'm also curious about this. Is there documentation about the recommended migration path from non-bootc managed images to bootc images?

**Comment by cgwalters** [comment]
> I'm also curious about this. Is there documentation about the recommended migration path from non-bootc managed images to bootc images?

We want it to basically just be `switch`. I think what you're running into here is basically https://bugzilla.redhat.com/show_bug.cgi?id=2308594

> @cgwalters I noticed https://github.com/containers/bootc/pull/137 recently got merged. Is the intended migration for existing ostree systems to use --replace-mode=alongside?

That's related for sure, but a bigger hammer as it will reset more things.

Anyways so I think this is a dup of https://github.com/containers/bootc/issues/632
