### ISSUE TITLE
Long upgrade status gives impression of frozen system

### ISSUE THREAD

**Issue by castrojo** [containers/bootc#885]
On a `bootc upgrade`, after the status bars finish downloading it appears that the IO part is next, which is writing to the disk, however there is no progress displayed on my screen:

![Image](https://github.com/user-attachments/assets/18e6dbd4-d875-4063-a407-403301266c63)

It was stuck like this for long enough to make me think that the entire process had locked up. After waiting the final progress summary was displayed. Everything is working fine, I think it's just a matter of communicating that 2nd longer operation better.

**Comment by cgwalters** [comment]
What version of bootc and ostree are you using?

This should already be fixed by https://github.com/containers/bootc/pull/848 *and* the real problem causing the delay was https://github.com/ostreedev/ostree/pull/3331

Can you retest with e.g. https://bodhi.fedoraproject.org/updates/FEDORA-2024-88b4110a60 and https://bodhi.fedoraproject.org/updates/FEDORA-2024-246828877f ?

**Comment by tulilirockz** [comment]
Im on these versions and that seems to be happening to me too. Ill test the latest bootc version to see if it works better
```
~/opt/bluefin> bootc --version                                                                                                                                              
bootc 1.1.0                                                                                                                                                                 
~/opt/bluefin> ostree --version                                                                                                                                             
libostree:                                                                                                                                                                  
 Version: '2024.8'                                                                                                                                                          
 Git: 4b9a78306b2437bd1d997be4c91ccd5f9b0a0d8a                                                                                                                              
 Features:                                                                                                                                                                  
  - inode64                                                                                                                                                                 
  - initial-var                                                                                                                                                             
  - libcurl                                                                                                                                                                 
  - libsoup3                                                                                                                                                                
  - gpgme                                                                                                                                                                   
  - composefs                                                                                                                                                               
  - ex-fsverity                                                                                                                                                             
  - libarchive                                                                                                                                                              
  - selinux                                                                                                                                                                 
  - openssl                                                                                                                                                                 
  - sign-ed25519                                                                                                                                                            
  - libmount                                                                                                                                                                
  - systemd                                                                                                                                                                 
  - release                                                                                                                                                                 
  - p2p            
```

**Comment by ryanabx** [comment]
> Im on these versions and that seems to be happening to me too. Ill test the latest bootc version to see if it works better
> 
> ```
> ~/opt/bluefin> bootc --version                                                                                                                                              
> bootc 1.1.0                                                                                                                                                                 
> ~/opt/bluefin> ostree --version                                                                                                                                             
> libostree:                                                                                                                                                                  
>  Version: '2024.8'                                                                                                                                                          
>  Git: 4b9a78306b2437bd1d997be4c91ccd5f9b0a0d8a                                                                                                                              
>  Features:                                                                                                                                                                  
>   - inode64                                                                                                                                                                 
>   - initial-var                                                                                                                                                             
>   - libcurl                                                                                                                                                                 
>   - libsoup3                                                                                                                                                                
>   - gpgme                                                                                                                                                                   
>   - composefs                                                                                                                                                               
>   - ex-fsverity                                                                                                                                                             
>   - libarchive                                                                                                                                                              
>   - selinux                                                                                                                                                                 
>   - openssl                                                                                                                                                                 
>   - sign-ed25519                                                                                                                                                            
>   - libmount                                                                                                                                                                
>   - systemd                                                                                                                                                                 
>   - release                                                                                                                                                                 
>   - p2p            
> ```

Looks like v1.1.2 is the latest version

**Comment by kfox1111** [comment]
I've noticed this too. If you already have most of the image already there, but just pulling a few small layers, the finalization step can dominate the time.

Mostly noticed on particularly slow drives, like using a usb thumb drive with a pi for doing some testing.

**Comment by cgwalters** [comment]
I believe this has been fixed. Please reopen if you disagree.
