### ISSUE TITLE
`bootc status` feedback

### ISSUE THREAD

**Issue by castrojo** [containers/bootc#900]
Discussed at kubecon but they're so minor that it's better to put them in one issue. Current status

```
[sudo] password for jorge: 
No staged image present
Current booted image: ghcr.io/ublue-os/bluefin-dx:stable
    Image version: 41.20241112.1 (2024-11-12 21:11:21 UTC)
    Image digest: sha256:9b4558a05315a855dffd3999c0693725a80754fa41b83ba536968b3e0e3afd5d
Current rollback image: ghcr.io/ublue-os/bluefin-dx:latest
    Image version: 41.20241108.0 (2024-11-08 04:43:34.141 UTC)
    Image digest: sha256:88b5636c07f05dbdd604634dfbdb9af6d7357cde0dbf731697b53acf95058920
```

A line feed to visually separate the stanzas would make it easier to differentiate. Colin wanted more sane timestamps. The dot from rpm-status is missed as well since it's been a pretty useful feature in the wild as the eye gravitates toward it. 

Also going to prototype a fancy version: https://github.com/ublue-os/bluefin/issues/1936

**Comment by cgwalters** [comment]
PR in https://github.com/containers/bootc/pull/901 - the unit tests shows what it looks like

**Comment by fiftydinar** [comment]
Looks very good now.

Technically, only this is missing compared to the `rpm-ostree status` output:

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 9h ago
```

I understand that bootc auto-update timer doesn't exist yet, so 2nd line is not there, but I find it useful to know the current state if `bootc update` is in the process or not.

**Comment by ver4a** [comment]
bootc 1.1.2 blocks with `Waiting for sysroot lock...` if upgrade is in progress
