### ISSUE TITLE
ERROR Linking tmp mounts to host: Exchanging /tmp <=> /tmp.tmp: Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by bigpod98** [containers/bootc#95]
I have hit this error `ERROR Linking tmp mounts to host: Exchanging /tmp <=> /tmp.tmp: Invalid cross-device link (os error 18)` with example image in install.md file, i am currently using ubuntu 23.04 as OS from which i run podman command using bootc built from source in git repo
if i mount /tmp to /tmp.tmp with podman run flag -v error changes to `ERROR Linking tmp mounts to host: Symlinking /proc/1/root//tmp to /tmp.tmp: File exists (os error 17)` mounting /tmp to /tmp changes error to `ERROR Linking tmp mounts to host: Exchanging /tmp <=> /tmp.tmp: Device or resource busy (os error 16)`

There might be some commonality with issue #91.

podman version 4.3.1

command: `sudo podman run --privileged --pid=host --net=none --security-opt label=type:unconfined_t ghcr.io/cgwalters/c9s-oscore bootc install --target-no-signature-verification /dev/vda`

**Comment by bigpod98** [comment]
with different image error also appeared as `ERROR Linking tmp mounts to host: Exchanging /var/tmp <=> /var/tmp.tmp: Invalid cross-device link (os error 18)`

**Comment by akdev1l** [comment]
`/proc/1/root//tmp` that looks like it is missing a component

**Comment by cgwalters** [comment]
This must be the same thing as https://github.com/containers/bootc/issues/91 so closing as a duplicate.

However, can you just show the output of `ls -ald /tmp && findmnt /tmp` on the host?
