### ISSUE TITLE
booting a bootc installed image on EFI boot based systems doesnt work

### ISSUE THREAD

**Issue by bigpod98** [containers/bootc#97]
I tried installing example image fount in install.md docs file, on efi based KVM VM. Simply said it doesnt boot with no information why not. even grub doesnt show up.
installing same image on BIOS based KVM VM boots no problem.

**Comment by bcrochet** [comment]
Can you share the error you received? Was it this?

```
error: boot data installation failed: installing component EFI: Updating EFI firmware variables: Clearing current EFI boot entry: Failed to invoke efibootmgr
ERROR Installing bootloader: Task Running bootupctl to install bootloader failed: ExitStatus(unix_wait_status(256))
```

**Comment by bigpod98** [comment]
sorry its been so long i dont have the error noted anymore

**Comment by bcrochet** [comment]
Was the invocation of bootc successful and upon reboot it failed?

**Comment by bigpod98** [comment]
yes, i belive so

**Comment by bcrochet** [comment]
i am unable to reproduce this. Without further info, this should probably be closed and reopened should a reproducer be found.

cc: @cgwalters

**Comment by bigpod98** [comment]
i agree
